name: generics-eot
version: "0.2.1.1"
synopsis: A library for generic programming that aims to be easy to understand
category: Generics
maintainer: "soenkehahn@gmail.com"
license: BSD3
github: soenkehahn/generics-eot

dependencies:
  - base == 4.*
  - markdown-unlit

extra-source-files:
  - README.md

ghc-options:
  - "-Wall -fno-warn-name-shadowing"
  - "-pgmL markdown-unlit"

library:
  exposed-modules:
    - Generics.Eot
    - Generics.Eot.Tutorial
  source-dirs:
    - src
  verbatim:
    build-tool-depends:
      "markdown-unlit:markdown-unlit"

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
      - examples
    dependencies:
      - hspec
      - QuickCheck
      - interpolate
      - doctest
    verbatim:
      build-tool-depends:
        "markdown-unlit:markdown-unlit, hspec-discover:hspec-discover"

  quickcheck:
    main: Spec.hs
    source-dirs:
      - test/quickcheck
      - src
    dependencies:
      - hspec
      - mockery
      - interpolate
      - shake
      - directory
      - filepath
      - QuickCheck
    verbatim:
      build-tool-depends:
        "markdown-unlit:markdown-unlit, hspec-discover:hspec-discover"
